# Generated by Django 5.2.6 on 2025-09-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_husband_women_husband'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
